export type GrowthTest = {
  name: string;
  date: string;
  effect: string;
  status: 'Shipped' | 'Not shipped';
  screenshot?: string;
};

export const growthTests: GrowthTest[] = [
  { name: 'Invite prompt after good money moments', date: 'Sep 2026', effect: 'Invites claimed −5%, not significant; group-balance warning.', status: 'Not shipped' },
  { name: 'Referral reward in the activity feed', date: 'Aug 2026', effect: 'Not read yet.', status: 'Not shipped' },
  { name: 'Receipt screen without a Done button (Android)', date: 'Sep 2026', effect: 'Shares +29.5% early; invites claimed +6%, not significant.', status: 'Not shipped' },
  { name: '“Double your salary” banner', date: 'Sep 2026', effect: 'No proven impact; early read was negative.', status: 'Shipped' },
  { name: 'New-user checklist (organic users)', date: 'Sep 2026', effect: 'First transaction +17–19%, significant.', status: 'Shipped' },
  { name: 'New-user checklist (referred users)', date: 'Sep 2026', effect: 'Positive but not significant.', status: 'Not shipped' },
  { name: 'Invite friends during signup', date: 'Aug 2026', effect: 'Not recorded.', status: 'Shipped' },
  { name: 'Share receipt after paying someone', date: 'Aug 2026', effect: 'Shares up 2–4×; signups positive but not significant.', status: 'Not shipped' },
  { name: 'Support card on USD account screen (Android)', date: 'Jul 2026', effect: 'Not recorded.', status: 'Shipped' },
  { name: 'Confirm button on country picker', date: 'Jul 2026', effect: 'No harm.', status: 'Not shipped' },
  { name: 'Invite tab in the tab bar (iOS)', date: 'Jul 2026', effect: 'Not recorded.', status: 'Not shipped' },
  { name: '“Earn $X” referral button (iOS)', date: 'Jul 2026', effect: 'Not recorded.', status: 'Not shipped' },
  { name: '“Converted to USD” labels on account details', date: 'Jul 2026', effect: 'No clear win; team will test the opposite instead.', status: 'Not shipped' },
  { name: 'USD account explainer', date: 'Jul 2026', effect: 'Not recorded.', status: 'Not shipped' },
  { name: 'Redesigned account details screen', date: 'Jul 2026', effect: 'Not recorded.', status: 'Shipped' },
  { name: 'Selfie tips before ID check (v2)', date: 'Jun 2026', effect: 'No impact either way.', status: 'Not shipped' },
  { name: 'Mexican account for US signups', date: 'Jun 2026', effect: 'Very little use and trending negative.', status: 'Shipped' },
  { name: 'Remove self-transfer option', date: 'Jun 2026', effect: 'Positive.', status: 'Shipped' },
  { name: 'Clearer transfer menu wording', date: 'Jun 2026', effect: 'More taps on Pay, fewer on self-transfer.', status: 'Not shipped' },
  { name: '“Get a US account” before choosing country', date: 'Jun 2026', effect: 'Opposite effect: more people signed up as US residents.', status: 'Shipped' },
  { name: 'Cashback on the card tab', date: 'Jun 2026', effect: 'No significant impact.', status: 'Shipped' },
  { name: 'CLABE “view details” as a button', date: 'Jun 2026', effect: 'Small impact.', status: 'Not shipped' },
  { name: 'Raise Mexico minimum deposit to 100 MXN', date: 'Jun 2026', effect: 'MXN deposits −20%.', status: 'Not shipped' },
  { name: 'Redesigned deposit account carousel', date: 'Jun 2026', effect: 'Not recorded.', status: 'Not shipped' },
  { name: '“No physical card, add to Apple Pay” nudge', date: 'Jun 2026', effect: 'Not recorded.', status: 'Shipped' },
  { name: 'Add money before seeing your card', date: 'Jun 2026', effect: 'Positive trend in money added on iOS; data issues on Android.', status: 'Not shipped' },
  { name: 'Copy-CLABE button on home (Mexico)', date: 'Jun 2026', effect: 'Not recorded.', status: 'Shipped' },
  { name: 'Apple Pay top-ups in Mexico', date: 'Jun 2026', effect: 'Positive.', status: 'Not shipped' },
  { name: 'Explainer before iOS tracking prompt', date: 'May 2026', effect: 'Not recorded.', status: 'Shipped' },
  { name: 'Transfers tab instead of floating button', date: 'May 2026', effect: 'Tab clearly won.', status: 'Shipped' },
  { name: 'Minimum deposit warning (Mexico)', date: 'Apr 2026', effect: 'Below-minimum deposits down a lot, no loss in deposits.', status: 'Shipped' },
  { name: 'New push permission screen', date: 'Apr 2026', effect: 'Very positive.', status: 'Shipped' },
  { name: 'Exchange rate on home screen', date: 'Mar 2026', effect: 'Broadly positive.', status: 'Not shipped' },
  { name: '“Buy dollars” button', date: 'Oct 2025', effect: 'Very negative after two days.', status: 'Shipped' },
  { name: 'Push prompt on app launch', date: 'Oct 2025', effect: 'Analysed too early.', status: 'Shipped' },
  { name: '“Add money” prompt after signup', date: 'Aug 2025', effect: 'Not significant.', status: 'Not shipped' },
  { name: 'Invite link in the home feed', date: 'Aug 2025', effect: 'Didn’t hit the +20% target.', status: 'Not shipped' },
  { name: 'Why-we-need-your-ID copy', date: 'Aug 2025', effect: 'No impact after 71 days.', status: 'Not shipped' },
  { name: 'Push request after SMS step', date: 'Undated', effect: 'iOS bug and Android data issues.', status: 'Not shipped' },
  { name: 'Welcome gift', date: 'Undated', effect: 'Shipped, then wound down.', status: 'Shipped' },
  { name: 'Paid referral programme (v1)', date: 'Sep 2025', effect: 'Shipped.', status: 'Shipped' },
  { name: 'Skippable contact sync at signup', date: 'Jan 2026', effect: 'Shipped.', status: 'Shipped' },
  { name: 'Mandatory contact sync at signup', date: 'Dec 2025', effect: 'Abandoned.', status: 'Not shipped' },
  { name: 'Card and account created at signup', date: 'Feb 2026', effect: 'Decided.', status: 'Not shipped' },
  { name: 'Hide card top-up in Mexico', date: 'Mar 2026', effect: 'Not shipped.', status: 'Not shipped' },
  { name: 'Smarty address search (outside US)', date: 'Mar 2026', effect: 'Decided.', status: 'Not shipped' },
  { name: 'Document check for US identity verification', date: 'Apr 2026', effect: 'Decided.', status: 'Not shipped' },
  { name: 'US subscription cashback', date: 'Mar 2026', effect: 'Not shipped.', status: 'Not shipped' },
  { name: 'Google address search in Mexico', date: 'May 2026', effect: 'Not shipped.', status: 'Not shipped' },
  { name: 'Auto-filled ID details (Mexico)', date: 'May 2026', effect: 'Decided / abandoned.', status: 'Not shipped' },
  { name: 'New address screen', date: 'May 2026', effect: 'Shipped.', status: 'Shipped' },
  { name: 'Feature interests before ID check', date: 'Jun 2026', effect: 'Shipped.', status: 'Shipped' },
  { name: '“Add money” when an investment buy is short', date: 'Jun 2026', effect: 'Shipped.', status: 'Shipped' },
  { name: 'Camera permission before ID check (Android)', date: 'Jun 2026', effect: 'Decided.', status: 'Not shipped' },
  { name: 'Invite tab in the tab bar (Android)', date: 'Jul 2026', effect: 'Decided.', status: 'Not shipped' },
  { name: '“Earn $X” referral button (Android)', date: 'Jul 2026', effect: 'Decided.', status: 'Not shipped' },
  { name: 'Highlight “No” on skip contact sync', date: 'Jul 2026', effect: 'Decided.', status: 'Not shipped' },
  { name: 'Help button during signup (Android)', date: 'Aug 2026', effect: 'Decided.', status: 'Not shipped' },
  { name: 'Selfie tips before ID check (v1)', date: 'Undated', effect: 'Replaced by v2.', status: 'Not shipped' },
  { name: 'Card creation timeline', date: 'Undated', effect: 'Archived.', status: 'Not shipped' },
];
