export type GrowthTest = {
  name: string;
  effect: string;
  status: 'Shipped' | 'Not shipped';
  screenshot?: string;
};

export const growthTests: GrowthTest[] = [
  { name: 'Invite prompt after good money moments', effect: 'Invites claimed −5%, not significant; group-balance warning.', status: 'Not shipped' },
  { name: 'Referral reward in the activity feed', effect: 'Not read yet.', status: 'Not shipped' },
  { name: 'Receipt screen without a Done button (Android)', effect: 'Shares +29.5% early; invites claimed +6%, not significant.', status: 'Not shipped' },
  { name: '“Double your salary” banner', effect: 'No proven impact; early read was negative.', status: 'Shipped' },
  { name: 'New-user checklist (organic users)', effect: 'First transaction +17–19%, significant.', status: 'Shipped' },
  { name: 'New-user checklist (referred users)', effect: 'Positive but not significant.', status: 'Not shipped' },
  { name: 'Invite friends during signup', effect: 'Not recorded.', status: 'Shipped' },
  { name: 'Share receipt after paying someone', effect: 'Shares up 2–4×; signups positive but not significant.', status: 'Not shipped' },
  { name: 'Support card on USD account screen (Android)', effect: 'Not recorded.', status: 'Shipped' },
  { name: 'Confirm button on country picker', effect: 'No harm.', status: 'Not shipped' },
  { name: 'Invite tab in the tab bar (iOS)', effect: 'Not recorded.', status: 'Not shipped' },
  { name: '“Earn $X” referral button (iOS)', effect: 'Not recorded.', status: 'Not shipped' },
  { name: '“Converted to USD” labels on account details', effect: 'No clear win; team will test the opposite instead.', status: 'Not shipped' },
  { name: 'USD account explainer', effect: 'Not recorded.', status: 'Not shipped' },
  { name: 'Redesigned account details screen', effect: 'Not recorded.', status: 'Shipped' },
  { name: 'Selfie tips before ID check (v2)', effect: 'No impact either way.', status: 'Not shipped' },
  { name: 'Mexican account for US signups', effect: 'Very little use and trending negative.', status: 'Shipped' },
  { name: 'Remove self-transfer option', effect: 'Positive.', status: 'Shipped' },
  { name: 'Clearer transfer menu wording', effect: 'More taps on Pay, fewer on self-transfer.', status: 'Not shipped' },
  { name: '“Get a US account” before choosing country', effect: 'Opposite effect: more people signed up as US residents.', status: 'Shipped' },
  { name: 'Cashback on the card tab', effect: 'No significant impact.', status: 'Shipped' },
  { name: 'CLABE “view details” as a button', effect: 'Small impact.', status: 'Not shipped' },
  { name: 'Raise Mexico minimum deposit to 100 MXN', effect: 'MXN deposits −20%.', status: 'Not shipped' },
  { name: 'Redesigned deposit account carousel', effect: 'Not recorded.', status: 'Not shipped' },
  { name: '“No physical card, add to Apple Pay” nudge', effect: 'Not recorded.', status: 'Shipped' },
  { name: 'Add money before seeing your card', effect: 'Positive trend in money added on iOS; data issues on Android.', status: 'Not shipped' },
  { name: 'Copy-CLABE button on home (Mexico)', effect: 'Not recorded.', status: 'Shipped' },
  { name: 'Apple Pay top-ups in Mexico', effect: 'Positive.', status: 'Not shipped' },
  { name: 'Explainer before iOS tracking prompt', effect: 'Not recorded.', status: 'Shipped' },
  { name: 'Transfers tab instead of floating button', effect: 'Tab clearly won.', status: 'Shipped' },
  { name: 'Minimum deposit warning (Mexico)', effect: 'Below-minimum deposits down a lot, no loss in deposits.', status: 'Shipped' },
  { name: 'New push permission screen', effect: 'Very positive.', status: 'Shipped' },
  { name: 'Exchange rate on home screen', effect: 'Broadly positive.', status: 'Not shipped' },
  { name: '“Buy dollars” button', effect: 'Very negative after two days.', status: 'Shipped' },
  { name: 'Push prompt on app launch', effect: 'Analysed too early.', status: 'Shipped' },
  { name: '“Add money” prompt after signup', effect: 'Not significant.', status: 'Not shipped' },
  { name: 'Invite link in the home feed', effect: 'Didn’t hit the +20% target.', status: 'Not shipped' },
  { name: 'Why-we-need-your-ID copy', effect: 'No impact after 71 days.', status: 'Not shipped' },
  { name: 'Push request after SMS step', effect: 'iOS bug and Android data issues.', status: 'Not shipped' },
  { name: 'Welcome gift', effect: 'Shipped, then wound down.', status: 'Shipped' },
  { name: 'Paid referral programme (v1)', effect: 'Shipped.', status: 'Shipped' },
  { name: 'Skippable contact sync at signup', effect: 'Shipped.', status: 'Shipped' },
  { name: 'Mandatory contact sync at signup', effect: 'Abandoned.', status: 'Not shipped' },
  { name: 'Card and account created at signup', effect: 'Decided.', status: 'Not shipped' },
  { name: 'Hide card top-up in Mexico', effect: 'Not shipped.', status: 'Not shipped' },
  { name: 'Smarty address search (outside US)', effect: 'Decided.', status: 'Not shipped' },
  { name: 'Document check for US identity verification', effect: 'Decided.', status: 'Not shipped' },
  { name: 'US subscription cashback', effect: 'Not shipped.', status: 'Not shipped' },
  { name: 'Google address search in Mexico', effect: 'Not shipped.', status: 'Not shipped' },
  { name: 'Auto-filled ID details (Mexico)', effect: 'Decided / abandoned.', status: 'Not shipped' },
  { name: 'New address screen', effect: 'Shipped.', status: 'Shipped' },
  { name: 'Feature interests before ID check', effect: 'Shipped.', status: 'Shipped' },
  { name: '“Add money” when an investment buy is short', effect: 'Shipped.', status: 'Shipped' },
  { name: 'Camera permission before ID check (Android)', effect: 'Decided.', status: 'Not shipped' },
  { name: 'Invite tab in the tab bar (Android)', effect: 'Decided.', status: 'Not shipped' },
  { name: '“Earn $X” referral button (Android)', effect: 'Decided.', status: 'Not shipped' },
  { name: 'Highlight “No” on skip contact sync', effect: 'Decided.', status: 'Not shipped' },
  { name: 'Help button during signup (Android)', effect: 'Decided.', status: 'Not shipped' },
  { name: 'Selfie tips before ID check (v1)', effect: 'Replaced by v2.', status: 'Not shipped' },
  { name: 'Card creation timeline', effect: 'Archived.', status: 'Not shipped' },
];
