const screenshotFiles: Record<string, string[]> = {
  'Invite prompt after good money moments': ['statsig_invite_nudge_celebrations_1_Test.jpg'],
  'Referral reward in the activity feed': ['statsig_show_referral_reward_in_tx_feed_for_referees_1__1.jpg'],
  'Receipt screen without a Done button (Android)': ['statsig_post_payment_receipt_hide_done_button_android_1_Control.jpg', 'statsig_post_payment_receipt_hide_done_button_android_2_Test.jpg'],
  '“Double your salary” banner': ['statsig_double_your_salary_ctas_1_Test.jpg'],
  'New-user checklist (organic users)': ['statsig_new_user_checklist_non_referred_users_1_Test.jpg'],
  'New-user checklist (referred users)': ['statsig_new_user_checklist_referred_users_1_Test.jpg'],
  'Invite friends during signup': ['statsig_signup_invite_friends_1_Test.jpg'],
  'Share receipt after paying someone': ['statsig_post_payment_receipt_share_1_Control.jpg', 'statsig_post_payment_receipt_share_2__2.jpg'],
  'Support card on USD account screen (Android)': ['statsig_virtual_account_support_card_android_1_Control.jpg', 'statsig_virtual_account_support_card_android_2_Test.jpg'],
  'Confirm button on country picker': ['statsig_idv_country_picker_confirm_step_1_Test.jpg'],
  'Invite tab in the tab bar (iOS)': ['statsig_referral_tab_1_Test.jpg'],
  '“Earn $X” referral button (iOS)': ['statsig_home_earn_referral_button_1_Control.jpg', 'statsig_home_earn_referral_button_2_Test.jpg'],
  '“Converted to USD” labels on account details': ['statsig_account_details_currency_conversion_subheadings_1__1.jpg', 'statsig_account_details_currency_conversion_subheadings_2__1.jpg'],
  'USD account explainer': ['statsig_usd_account_onboarding_1_Test_Onb.jpg'],
  'Redesigned account details screen': ['statsig_deposit_accounts_v2_1_Control.jpg', 'statsig_deposit_accounts_v2_2_Test.jpg'],
  'Selfie tips before ID check (v2)': ['statsig_idv_intro_tips_v2_1_Test.jpg'],
  'Mexican account for US signups': ['statsig_us_show_mxn_account_1_Test.jpg'],
  'Remove self-transfer option': ['statsig_remove_transfer_option_1_Control.jpg', 'statsig_remove_transfer_option_2_Test.jpg'],
  'Clearer transfer menu wording': ['statsig_transfer_menu_copy_1_Control.jpg', 'statsig_transfer_menu_copy_2_Test.jpg'],
  '“Get a US account” before choosing country': ['statsig_pre_country_selection_1_Control.jpg', 'statsig_pre_country_selection_2__2.jpg'],
  'Cashback on the card tab': ['statsig_card_home_cashback_1_Control.jpg', 'statsig_card_home_cashback_2_Test.jpg'],
  'CLABE “view details” as a button': ['statsig_mx_clabe_view_details_button_1_Control.jpg', 'statsig_mx_clabe_view_details_button_2_Test.jpg'],
  'Raise Mexico minimum deposit to 100 MXN': ['statsig_change_mxn_deposit_minimum_to_100_1_Test.jpg'],
  'Redesigned deposit account carousel': ['statsig_redesign_deposit_accounts_carousel_1_Control.jpg', 'statsig_redesign_deposit_accounts_carousel_2_Test.jpg'],
  '“No physical card, add to Apple Pay” nudge': ['statsig_card_apple_pay_nudge_1_Test.jpg'],
  'Add money before seeing your card': ['statsig_card_empty_state_add_money_v2_1_Test.jpg'],
  'Copy-CLABE button on home (Mexico)': ['statsig_mx_home_clabe_deposit_card_1_Test.jpg'],
  'Apple Pay top-ups in Mexico': ['statsig_mx_apple_pay_international_cards_1_Test.jpg'],
  'Explainer before iOS tracking prompt': ['statsig_att_primer_screen_1_Test.jpg'],
  'Transfers tab instead of floating button': ['statsig_move_fab_into_tab_bar_1_Control.jpg', 'statsig_move_fab_into_tab_bar_2_Test.jpg'],
  'Minimum deposit warning (Mexico)': ['statsig_mx_clabe_minimum_payment_copy_warning_1_Test.jpg'],
  'New push permission screen': ['statsig_push_opt_in_v2_1_Test.jpg'],
  'Exchange rate on home screen': ['statsig_exchange_rate_on_home_screen_1_Test.jpg'],
  '“Buy dollars” button': ['statsig_buy_dollars_1_Test.jpg', 'statsig_buy_dollars_2_1_Test.jpg'],
  'Push prompt on app launch': ['statsig_show_push_notification_prompt_onstartup_1_Control.jpg', 'statsig_show_push_notification_prompt_onstartup_2_Test.jpg'],
  '“Add money” prompt after signup': ['statsig_signup_done_add_money_cta_1_Control.jpg', 'statsig_signup_done_add_money_cta_2_Test.jpg'],
  'Invite link in the home feed': ['statsig_share_invite_link_on_home_feed_1_Control.jpg', 'statsig_share_invite_link_on_home_feed_2_Test.jpg'],
  'Why-we-need-your-ID copy': ['statsig_idv_copy_change_1_Control.jpg', 'statsig_idv_copy_change_2_Test.jpg'],
  'Push request after SMS step': ['statsig_notification_permission_after_sending_sms_1_Control.jpg', 'statsig_notification_permission_after_sending_sms_2_Test.jpg'],
};

export function getGrowthScreenshots(name: string) {
  return (screenshotFiles[name] ?? []).map((file) => `/growth-tests/${file}`);
}
